language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
xcode_project: CRToastDemo.xcodeproj
xcode_scheme: CRToastTests
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
  - iphonesimulator8.0
