language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
xcode_workspace: Example/CRToastDemo.xcworkspace
xcode_scheme: CRToastTests
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
  - iphonesimulator8.1
